"""
Evidence-Gated Advisor — LLM prompt builder that may only reference
evidence generated by the app. No inference beyond provided data.

Evidence types:
  - WheelDecision (scored contracts / positions)
  - Macro regime
  - IV environment
  - Earnings calendar
  - Probability of Profit (PoP)
  - Technical regime
  - Portfolio context

If evidence for a category is missing, the advisor must answer "unknown"
rather than hallucinate.
"""

import logging
from dataclasses import dataclass, field, asdict
from datetime import datetime

logger = logging.getLogger(__name__)


@dataclass
class EvidenceBlock:
    category: str = ""
    label: str = ""
    content: str = ""
    source: str = ""
    available: bool = False
    fetched_at: str = ""

    def to_prompt_line(self) -> str:
        if not self.available or not self.content:
            return f"[{self.label}] unknown — no data available"
        return f"[{self.label}] {self.content}"


@dataclass
class WheelAdvisorEvidence:
    portfolio: EvidenceBlock = field(default_factory=lambda: EvidenceBlock(category="portfolio", label="Portfolio"))
    positions: EvidenceBlock = field(default_factory=lambda: EvidenceBlock(category="positions", label="Open Positions"))
    opportunities: EvidenceBlock = field(default_factory=lambda: EvidenceBlock(category="opportunities", label="Top Opportunities"))
    signal_overlays: EvidenceBlock = field(default_factory=lambda: EvidenceBlock(category="signal_overlays", label="Multi-Dimensional Signal Overlay"))
    macro: EvidenceBlock = field(default_factory=lambda: EvidenceBlock(category="macro", label="Macro Regime"))
    vix: EvidenceBlock = field(default_factory=lambda: EvidenceBlock(category="vix", label="VIX Regime"))
    iv_environment: EvidenceBlock = field(default_factory=lambda: EvidenceBlock(category="iv", label="IV Environment"))
    earnings: EvidenceBlock = field(default_factory=lambda: EvidenceBlock(category="earnings", label="Earnings Calendar"))
    technical: EvidenceBlock = field(default_factory=lambda: EvidenceBlock(category="technical", label="Technical Regime"))
    playbook_hypotheses: EvidenceBlock = field(default_factory=lambda: EvidenceBlock(category="playbook", label="Active Playbook Hypotheses"))
    scan_ledger: EvidenceBlock = field(default_factory=lambda: EvidenceBlock(category="scan", label="Recent Scan Summary"))

    def all_blocks(self) -> list[EvidenceBlock]:
        return [
            self.portfolio, self.positions, self.opportunities,
            self.signal_overlays, self.macro, self.vix, self.iv_environment,
            self.earnings, self.technical,
            self.playbook_hypotheses, self.scan_ledger,
        ]

    def to_prompt(self) -> str:
        lines = ["=== EVIDENCE FOR WHEEL ADVISOR ==="]
        lines.append(f"Generated at: {datetime.now().isoformat()}")
        lines.append("IMPORTANT: You may ONLY reference the evidence below.")
        lines.append("If evidence for a category says 'unknown', answer 'unknown'.")
        lines.append("Do not infer or guess missing data.")
        lines.append("")
        for block in self.all_blocks():
            lines.append(block.to_prompt_line())
        lines.append("")
        lines.append("---")
        lines.append(
            "Based ONLY on the evidence above, provide specific trade suggestions for: "
            "OPENING new covered calls or CSPs, CLOSING positions that have reached "
            "profit targets, and ROLLING positions under pressure. "
            "For each suggestion, mention the ticker, strike, expiration, and "
            "which specific evidence supports the suggestion. "
            "If evidence is missing or says 'unknown', state that clearly."
        )
        return "\n".join(lines)


def build_evidence_from_context(context: dict) -> WheelAdvisorEvidence:
    evidence = WheelAdvisorEvidence()

    pf = context.get("portfolio", {})
    if pf.get("account_value"):
        evidence.portfolio = EvidenceBlock(
            category="portfolio", label="Portfolio",
            content=f"Account value: ${pf['account_value']:,.2f}, Available cash: ${pf.get('available_cash', 0):,.2f}",
            source="moomoo", available=True, fetched_at=datetime.now().isoformat(),
        )

    pos = context.get("positions", [])
    if pos:
        lines = []
        for s in pos:
            lines.append(f"{s['ticker']}: {s['shares']} shares @ ${s['avg_cost']:.2f} avg, current ${s['market_price']:.2f}")
        evidence.positions = EvidenceBlock(
            category="positions", label="Open Positions",
            content=" | ".join(lines), source="moomoo",
            available=True, fetched_at=datetime.now().isoformat(),
        )

    opt = context.get("scored_positions", [])
    if opt:
        lines = []
        for o in sorted(opt, key=lambda x: x.get("roll_pressure", 0), reverse=True):
            parts = [
                f"{o['ticker']} {o['option_type']} ${o['strike']:.1f} exp {o['expiration']} DTE={o['dte']}",
                f"stock=${o['stock_price']:.2f} OTM={o['otm_pct']:.1f}%",
                f"mid=${o['mid_price']:.2f} roll_pressure={o['roll_pressure']:.0f}%",
                f"profit_progress={o['profit_target_progress']:.0f}%",
            ]
            if o.get("warnings"):
                parts.append(f"warnings={'; '.join(o['warnings'])}")
            lines.append(" | ".join(parts))
        evidence.positions = EvidenceBlock(
            category="scored_positions", label="Open Positions (Scored)",
            content="\n".join(lines), source="wheel_decision",
            available=True, fetched_at=datetime.now().isoformat(),
        )

    opp = context.get("opportunities", [])
    if opp:
        lines = []
        for i, r in enumerate(opp[:5]):
            overlay = r.get("signal_overlay") or {}
            overlay_bits = []
            if overlay:
                overlay_bits.append(f"overlay={overlay.get('verdict', 'unknown')} {overlay.get('summary', '')}".strip())
                capital = overlay.get("capital", {}) or {}
                technical = overlay.get("technical", {}) or {}
                derivatives = overlay.get("derivatives", {}) or {}
                if capital.get("summary"):
                    overlay_bits.append(f"capital={capital.get('summary')}")
                if technical.get("summary"):
                    overlay_bits.append(f"technical={technical.get('summary')}")
                if derivatives.get("summary"):
                    overlay_bits.append(f"derivatives={derivatives.get('summary')}")
                if r.get("signal_overlay_fit") and r.get("signal_overlay_fit") != "unknown":
                    overlay_bits.append(f"fit={r.get('signal_overlay_fit')}")
            lines.append(
                f"#{i+1} {r['ticker']} {r['option_type']} ${r['strike']:.1f} "
                f"exp {r['expiration']} premium=${r['premium_per_contract']:.2f} "
                f"delta={r['delta']:.3f} DTE={r['dte']} "
                f"ann_return={r['annualized_return']:.1f}% score={r['score']:.0f}"
                + (f" | {' | '.join(overlay_bits)}" if overlay_bits else "")
            )
        evidence.opportunities = EvidenceBlock(
            category="opportunities", label="Top Opportunities",
            content="\n".join(lines), source="wheel_scorer",
            available=True, fetched_at=datetime.now().isoformat(),
        )

    signal_overlays = context.get("signal_overlays", [])
    if signal_overlays:
        lines = []
        for item in signal_overlays[:5]:
            overlay = item.get("overlay") or {}
            capital = overlay.get("capital", {}) or {}
            technical = overlay.get("technical", {}) or {}
            derivatives = overlay.get("derivatives", {}) or {}
            parts = [
                f"{item.get('ticker', 'UNKNOWN')}",
                f"verdict={overlay.get('verdict', 'unknown')}",
                f"bias={overlay.get('bias', 'unknown')}",
            ]
            if overlay.get("summary"):
                parts.append(f"summary={overlay.get('summary')}")
            if capital.get("summary"):
                parts.append(f"capital={capital.get('summary')}")
            if technical.get("summary"):
                parts.append(f"technical={technical.get('summary')}")
            if derivatives.get("summary"):
                parts.append(f"derivatives={derivatives.get('summary')}")
            if item.get("fit") and item.get("fit") != "unknown":
                parts.append(f"fit={item.get('fit')}")
            if item.get("warnings"):
                parts.append(f"warnings={'; '.join(item.get('warnings', []))}")
            lines.append(" | ".join(parts))
        evidence.signal_overlays = EvidenceBlock(
            category="signal_overlays",
            label="Multi-Dimensional Signal Overlay",
            content="\n".join(lines),
            source="moomoo",
            available=True,
            fetched_at=datetime.now().isoformat(),
        )

    macro = context.get("macro", {})
    if macro:
        lines = [
            f"Rates: {macro.get('rate_regime', 'unknown')}",
            f"Credit stress: {macro.get('credit_stress', 'unknown')}",
            f"Growth: {macro.get('growth_regime', 'unknown')}",
            f"Inflation: {macro.get('inflation_trend', 'unknown')}",
            f"Yield curve: {macro.get('yield_curve_slope', 'N/A')}",
            f"Summary: {macro.get('summary', 'N/A')}",
        ]
        evidence.macro = EvidenceBlock(
            category="macro", label="Macro Regime",
            content=" | ".join(lines), source=macro.get("source", "FRED"),
            available=True, fetched_at=datetime.now().isoformat(),
        )

    vix = context.get("vix", {})
    if vix:
        evidence.vix = EvidenceBlock(
            category="vix", label="VIX Regime",
            content=f"VIX: {vix.get('vix', 'N/A')} ({vix.get('regime', 'unknown')}) — {vix.get('description', '')}",
            source=vix.get("source", "yahoo"),
            available=True, fetched_at=datetime.now().isoformat(),
        )

    return evidence
